### PR TITLE
Create uighur_arabic.yml

### PR DESCRIPTION
**Pull request by tventimi**
A table for the Uighur language using the Arabic script, based on the MS Word version of LOC's mapping table: https://www.loc.gov/catdir/cpso/romanization/uighur.docx.  The mappings in the table incorporate points 1, 2, and 3 under "Rules of Application", but no specific words and examples (i.e., the table only captures the rules, not the exceptions, if any).

### CODE REVIEW

**Comment by scossu** [comment]
@tventimi Thanks for the addition. 

Do you have a handful of test strings to run automated tests on? Something along the lines of https://github.com/lcnetdev/scriptshifter/blob/main/tests/data/script_samples/arabic.csv 

Also: does Uighur have complex vocalization rules as other Arabic scripts, that this table may not be able to address?

**Comment by scossu** [comment]
One more thing: 

Skimming over the reference doc you linked I see this rule: 

> Use the single prime ( ʹ ) to separate two letters representing two distinct consonantal sounds when the combination might be read as a digraph.
> uzʹhal ئۇزﻫﺎل

Does the table take this into account? It should be possible to either include hard-coded mappings such as 

```
"زﻫ":  "zʹh"
```
or, if there are too many combinations, make a simple hook that every time it sees a consonant, checks if the next letter is a consonant too, and adds the prime chracter.

**Comment by tventimi** [comment]
Hi Stefano,

Thanks for your response.  I do attempt to take the digraph rule into account, though the example you gave indicates I must have missed some combinations.  At the end of the file, there are a set of mappings where the romanization includes "\u02B9".  This is the single prime character.  Basically, for all each digraph (ng, ch, sh, kh, zh, gh), I generate a line for each possible combination of the two consonants.  So, for example, for any of the "z" characters followed by any of the "h" characters, I map each combination to "z\u02B9h".

That being said, the example you gave (which I assume is taken from the examples in the LOC file), contains a form of "z" (\u0632) not found in table section of the file.  I don't know enough about the language to know why this would be, but I can see if one of my colleagues could provide more insight.

As for examples, I do have a few examples of DLC records from WorldCat that contain parallel Roman/Arabic text for Uighur, but I cannot verify their accuracy.  Let me see if I can.  I will get back to you.

Tom

**Comment by scossu** [comment]
OK, so, from what I gather the digraphs are a relatively manageable number, and you already included them (except maybe the one that I brought up), correct? 

And yes, I took that example from the ALA-LC spec sheet.

**Comment by tventimi** [comment]
Hi Stefano,

Sorry for the delay in replying.  Yes, it does seem like a manageable number, and I included all permutations of the characters in the LOC table.  But I have not yet been able to find someone with real knowledge of this script who can confirm if there is anything else missing.  Princeton is currently in the process of hiring a Uighur specialist, which hopefully will happen later this year.  So, I could most likely find out more at that time.  We could revisit this then if you want.

Tom

**Comment by scossu** [comment]
I guess it would be safe to merge, so Uighur experts can test more easily. 

In order for this to work, however, the table needs an entry added to the index: https://github.com/lcnetdev/scriptshifter/blob/main/scriptshifter/tables/data/index.yml

**Comment by tventimi** [comment]
Thanks, Stefano, and I agree, having this in place will make it easier to get feedback once we hire an Uighur specialist.  I updated the language index file you indicated and added it to the same branch (tventimi:patch-2).  Should I close and recreate this PR to include that change?

**Comment by scossu** [comment]
No, that should be fine. Just one more question, to be sure: is it OK if the MARC code `uig` is the same for both Arabic and Cyrillic scripts?

**Comment by tventimi** [comment]
Yes, that is fine.  There are other cases where multiple ScriptShifter languages are associated with the same MARC code.  In such cases, if Parallelogram is trying to autodetect the language, it will just select the first one alphabetically that matches, and the user can select a different one if needed.

**Review by scossu — APPROVED** [review]

**Pull request merged**
