### PR TITLE
Update azerbaijani.yml

### LINKED ISSUE #14: Azerbaijani (Cyrillic)  Kazakh (Cyrillic)  Kyrgyz (Cyrillic)  Tajik (Cyrillic)  Tatar (Cyrillic)  Uzbek (Cyrillic)
I have tested this language over and over again and also managed to get the screenshots of the books to make sure that nothing is missed. I really like the script shifter and was hoping that it would work well for Cyrillic Azeri since Latin Azeri was not part of it. But as I mentioned earlier unfortunately it doesn't work for certain letters. I will try to if I can insert the examples : This is the title of the book (LCCN#00655035 ) in original Azeri Cyrillic ( I have a screenshot of the cover and title page) Азəрбајҹан Совет əдəбијјатынын поетика мəсəлəлəри : ǂb елми əсəрлəрин тематик мəҹмyеси This is how the ScriptShifter romanized it Azərbai̐jan Sovet ədəbиi̐i̐atыnыn poetиka məsələlərи : ǂb elmи əsərlərиn tematиk məjmyesи This is how correctly it should have been romanized based on LC-ALA romanization table Azărbai̐jan Sovet ădăbii̐i̐atynyn poetika măsălălări : ǂb elmi ăsărlărin tematik măjmu̇esi I will highlight which of the letters were correctly romanized and which failed: This how this letter looks like in the table: Vernacular Romanization ә ă While in some other instances this letter was romanized fine in this particular case as you can see it stayed as vernacular during the romanization process. These two letters: ј,ҹ were romanized correctly both in the 1st word of the tile and others based on the table: ј i̐ ҹ j The next incorrectly romanized letter is a basic и which should be represented by i и i The next incorrect letter is ы which should have been romanized as y ы y The last incorrect letter which is contained in the last word "мəҹмyеси" is the letter "ү" which should have been romanized as u̇ ү u̇ I want to repeat that I have tested several titles. This is a second example: Азәрбајҹан XXI әсрин астанасында" Республика елми-практики конфрансынын : материаллары Azărbai̐jan XXI ăsrиn astanasыnda" Respublиka elmи-praktиkи konfransыnыn : materиallarы The set of letters here is more limited but the in accuracies with the romanization are almost the same. What surprised me here was the fact that ә in the first word "Азәрбајҹан" was romanized correctly which was not a case in previous example. BBut the problem with the letters и and ы stayed the same.

### PR DESCRIPTION
**Pull request by rrroche**
Part of Fixes #14 

Added Latin Schwa (ə U+0259 and Ə U+018F) as a presumed mistype of the Cyrillic Schwa

### CODE REVIEW

**Comment by scossu** [comment]
@rrroche are you going to add the roman-to-script transliteration too?

**Comment by rrroche** [comment]
Sorry to take so long to respond. No, I am not going to add the roman-to-script transliteration. I do not think it is needed, the character I added is correcting a mistype rather than adding a new valid character, so transliterating back to script should always go to the correct character, which you already have.

Thanks for checking!

**Review by scossu — APPROVED** [review]

**Comment by scossu** [comment]
I see now this is to fix a possible mistype. All good. 

Separately, we may want to address the fact that we are producing romanized text with separate combining diacritics, rather than single-character diacritic letters. We discussed this with @RandyBarry and we may want to go back to it in a systematic way later.

**Comment by scossu** [comment]
I see now this is to fix a possible mistype. All good. 

Separately, we may want to address the fact that we are producing romanized text with separate combining diacritics, rather than single-character diacritic letters. We discussed this with @RandyBarry and we may want to go back to it in a systematic way later.

**Pull request merged**
